<?php

namespace ContainerFFgRtQd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Awl7YVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.awl7_YV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.awl7_YV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'slugify' => ['privates', 'Cocur\\Slugify\\Slugify', 'getSlugifyService', true],
        ], [
            'slugify' => 'Cocur\\Slugify\\Slugify',
        ]);
    }
}
