<?php

namespace ContainerFFgRtQd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlbum1RepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\Album1Repository' shared autowired service.
     *
     * @return \App\Repository\Album1Repository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\Album1Repository'] = new \App\Repository\Album1Repository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
