<?php

namespace ContainerFFgRtQd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGlavControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GlavController' shared autowired service.
     *
     * @return \App\Controller\GlavController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\GlavController'] = $instance = new \App\Controller\GlavController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\GlavController', $container));

        return $instance;
    }
}
