<?php

namespace ContainerXHsoP0h;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlbumFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AlbumFormType' shared autowired service.
     *
     * @return \App\Form\AlbumFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AlbumFormType'] = new \App\Form\AlbumFormType();
    }
}
