<?php

namespace ContainerXHsoP0h;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlugifyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Cocur\Slugify\Slugify' shared autowired service.
     *
     * @return \Cocur\Slugify\Slugify
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Cocur\\Slugify\\Slugify'] = new \Cocur\Slugify\Slugify();
    }
}
