<?php

namespace App\Form\Type\Dropzone;

use App\Controller\AddPhotosController;
use App\Repository\ImgRepository;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\FormInterface;

class DropzoneType extends AbstractType
{

    public function __construct(
        private ImgRepository $ImgRepository
    ){
    }

    final public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'dropzone',
            CollectionType::class,
            [
                'entry_type' => HiddenType::class,
                'label' => false,
                'allow_add' => true,
                'allow_delete' => true,

                'attr' => [
                    'class' => 'dropzone',
                    'id' => 'dropzone',
                    'action' => '/img/upload',
                ],

            ])
            ->add('submit', SubmitType::class, [
                    'label' => 'Добавить',
                    'attr' => array(
                        'class' => 'button',
                        'onclick' => 'upload()'
                    ),
                ]

            )
         ->addModelTransformer(new DropzoneTransformer($this->ImgRepository, $options['once']));

        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    final public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'once' => false,
            'maxFiles' => 10
        ]);

        parent::configureOptions($resolver);
    }

    final public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['id'] = $options['attr']['id'];
        $view->vars['maxFiles'] = $options['maxFiles'];
        $view->vars['img'] = [];

    }
}
