<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOel3fD4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOel3fD4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOel3fD4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOel3fD4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOel3fD4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Oel3fD4',
    'container.build_id' => '747c7c7d',
    'container.build_time' => 1636807619,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOel3fD4');
