<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPLyTPux\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPLyTPux/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPLyTPux.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPLyTPux\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPLyTPux\App_KernelDevDebugContainer([
    'container.build_hash' => 'PLyTPux',
    'container.build_id' => '96b12a29',
    'container.build_time' => 1636578734,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPLyTPux');
